# Site settings
title: OAE Project
email: info@oaeproject.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oaeproject.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--more-->
comments: true

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      banner: /assets/img/banners/why-oae-matters.png
      author_image: /assets/img/authors/nicolaas.png
